# Generated by Django 5.2.7 on 2025-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('email', models.EmailField(default='staff@gmail.com', max_length=254, unique=True)),
                ('password', models.CharField(default='1234', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
